In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("homeprices.csv")

In [4]:
df.head()

,area,bedrooms,age,price
0,2600,3.0,20,550000
1,3000,4.0,15,565000
2,3200,NaN,18,610000
3,3600,3.0,30,595000
4,4000,5.0,8,760000


In [5]:
median_bedrooms=df.bedrooms.median()

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [7]:
df

,area,bedrooms,age,price
0,2600,3.0,20,550000
1,3000,4.0,15,565000
2,3200,4.0,18,610000
3,3600,3.0,30,595000
4,4000,5.0,8,760000
5,4100,6.0,8,810000


In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)



LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

np.float64(221323.0018654043)

In [11]:
reg.predict([[2500,4,5]])

C:\Users\gmadh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [12]:
import pickle

In [16]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [17]:
with open('model_pickle','rb') as f:
    model=pickle.load(f)

In [20]:
model.predict([[25000,6,8]])

C:\Users\gmadh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3137363.58761734])

In [22]:
import joblib

In [23]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [24]:
model=joblib.load("model_joblib")
model.predict([[2500,4,5]])

C:\Users\gmadh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])